#
# Add project labels to PRs
# Invocation is done by .github/workflows/prlabeler.yml

'type:docs':
- changed-files:
  - any-glob-to-any-file: 'book_source/**'
  - any-glob-to-any-file: 'documentation/**'
  - any-glob-to-any-file: 'CONTRIBUTING.md'
  - any-glob-to-any-file: 'DEBUGING.md'
  - any-glob-to-any-file: 'DEV-INTRO.md'
  - any-glob-to-any-file: 'README.md'

'area:infrastructure':
- changed-files:
  - any-glob-to-any-file: 'docker/**'
  - any-glob-to-any-file: '.github/workflows/**'

'area:ui':
- changed-files:
  - any-glob-to-any-file: 'web/**'

'area:core':
- changed-files:
  - any-glob-to-any-file: 'base/**'

'area:models':
- changed-files:
  - any-glob-to-any-file: 'models/**'

'area:modules':
- changed-files:
  - any-glob-to-any-file: 'modules/**'

# TODO: scripts folder is due for a reorganization by theme;
# update these tags when that is done
'area:scripts':
- changed-files:
  - any-glob-to-any-file: 'scripts/**'

'type:test':
- all:
  - changed-files:
    - any-glob-to-any-file: ['tests/**', '**/tests/**']
    - any-glob-to-any-file: '!**/tests/Rcheck_reference.log'
